apiVersion: karpenter.k8s.aws/v1
kind: EC2NodeClass
metadata:
  name: stateful
  namespace: karpenter
spec:
  amiSelectorTerms:
    - alias: al2023@latest
  role: "KarpenterNodeRole-eks-terraform"
  subnetSelectorTerms:
    - tags:
        karpenter.sh/discovery: "eks-terraform"
  securityGroupSelectorTerms:
    - tags:
        karpenter.sh/discovery: "eks-terraform"
  userData: |
    #!/bin/bash
    echo "eks-terraform" > /etc/eks/cluster-name
  tags:
    Name: "karpenter-stateful-eks-terraform"
    Environment: "production"
    ManagedBy: "karpenter"
    NodePool: "stateful"
  metadataOptions:
    httpEndpoint: enabled
    httpProtocolIPv6: disabled
    httpPutResponseHopLimit: 2
    httpTokens: required
  blockDeviceMappings:
    - deviceName: /dev/xvda
      ebs:
        volumeSize: 50Gi
        volumeType: gp3
        encrypted: true
        deleteOnTermination: true
