apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: monitoring

resources:
  - https://raw.githubusercontent.com/grafana/mimir/v2.11.0/operations/kubernetes/manifests/kustomization.yaml
  - application.yml
