apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/wiktorkowalski/eks-terraform.git
    targetRevision: HEAD
    path: k8s/ingress/
  destination:
    server: https://kubernetes.default.svc
    # namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
