apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

resources:
  - argocd-app.yaml
  - karpenter-app.yaml
  - traefik-app.yaml
  - cert-manager-app.yaml
  - external-dns-app.yaml
  - monitoring-app.yaml
  - dashboard-app.yaml
