apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

helmCharts:
  - name: argocd
    version: 7.3.10
    releaseName: argo-cd
    repo: https://argoproj.github.io/argo-helm
    

resources:
  - repo-secret.yml
  - application.yml
