apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd
resources:
- argocd-namespace.yml
- https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml
- repo-secret.yml
- application.yml


# patches:
# - path: argocd-patch.yml