apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

resources:
  - namespace.yml
  - https://raw.githubusercontent.com/argoproj/argo-cd/v2.14.2/manifests/install.yaml
  - application.yml
  - repo-secret.yml

patches:
  - target:
      kind: Deployment
      name: argocd-server
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/args
        value:
          - /usr/local/bin/argocd-server
          - --insecure
  - target:
      kind: ConfigMap
      name: argocd-cmd-params-cm
    patch: |-
      - op: add
        path: /data
        value:
          server.insecure: "true"
