apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kube-system
resources:
- https://github.com/kubernetes-sigs/aws-load-balancer-controller/releases/download/v2.8.1/v2_8_1_full.yaml
- application.yml

patchesStrategicMerge:
  - |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: aws-load-balancer-controller
      namespace: kube-system
    spec:
      template:
        spec:
          containers:
            - name: controller
              args:
                - --cluster-name=eks-terraform
                - --aws-region=eu-west-1
  - |-
    apiVersion: v1
    kind: ServiceAccount
    metadata:
      name: aws-load-balancer-controller-sa
      namespace: kube-system
      annotations:
        eks.amazonaws.com/role-arn: arn:aws:iam::942892246732:role/main-eks-node-group-20240722080512872100000003