apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kube-system

resources:
- https://github.com/jetstack/cert-manager/releases/download/v1.12.3/cert-manager.yaml
- application.yml